/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'service' : string,
  'status' : ApplicationStatus,
  'applicantName' : string,
  'documents' : Array<Document>,
  'rejection' : [] | [RejectionInfo],
  'stage' : bigint,
  'phoneNumber' : string,
  'price' : [] | [bigint],
  'transactionId' : [] | [string],
}
export interface ApplicationFormData {
  'id' : string,
  'service' : string,
  'applicantName' : string,
  'documents' : Array<Document>,
  'phoneNumber' : string,
}
export type ApplicationStatus = { 'submitted' : null } |
  { 'feeSet' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'paymentVerifying' : null } |
  { 'paymentPending' : null };
export interface Document { 'content' : ExternalBlob, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface ManagerNotification {
  'message' : string,
  'timestamp' : bigint,
}
export interface RejectionInfo { 'timestamp' : bigint, 'reason' : string }
export interface Service {
  'name' : string,
  'serviceId' : bigint,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canUserPay' : ActorMethod<[string], boolean>,
  'clearNotification' : ActorMethod<[bigint], boolean>,
  'confirmPayment' : ActorMethod<[string, string], boolean>,
  'getActivePaymentPrice' : ActorMethod<[], bigint>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getAllNotifications' : ActorMethod<[], Array<ManagerNotification>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getApplication' : ActorMethod<[string], [] | [Application]>,
  'getApplicationFee' : ActorMethod<[string], [] | [bigint]>,
  'getApplicationsByStatus' : ActorMethod<
    [ApplicationStatus, string],
    Array<Application>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getManagerNotifications' : ActorMethod<[], Array<ManagerNotification>>,
  'getPaymentDetails' : ActorMethod<
    [],
    { 'qr' : [] | [ExternalBlob], 'upiDetails' : string, 'amount' : bigint }
  >,
  'getPaymentIntentURL' : ActorMethod<[], string>,
  'getRejectionReason' : ActorMethod<[string], [] | [RejectionInfo]>,
  'getServicePrice' : ActorMethod<[bigint], [] | [bigint]>,
  'getUserApplications' : ActorMethod<[string, string], Array<Application>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPaymentActive' : ActorMethod<[], boolean>,
  'rejectApplication' : ActorMethod<[string, string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setActivePrice' : ActorMethod<[bigint], undefined>,
  'setApplicationFee' : ActorMethod<[string, bigint, string], boolean>,
  'setPaymentQR' : ActorMethod<[ExternalBlob], undefined>,
  'setServicePrice' : ActorMethod<[bigint, string, bigint, string], boolean>,
  'submitApplication' : ActorMethod<[ApplicationFormData], Application>,
  'submitPayment' : ActorMethod<[string, string], boolean>,
  'updateApplicationStage' : ActorMethod<[string, bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];