/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'service' : string,
  'status' : ApplicationStatus,
  'documents' : Array<Document>,
  'name' : string,
  'phoneNumber' : string,
  'price' : [] | [bigint],
}
export type ApplicationStatus = { 'awaitingPrice' : null } |
  { 'completed' : null } |
  { 'paymentPendingVerification' : null } |
  { 'documentsUploaded' : null } |
  { 'priceSet' : null };
export interface Document { 'content' : ExternalBlob, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Submit application with documents (documentsUploaded state)
   */
  'addApplication' : ActorMethod<
    [string, string, string, string, Array<Document>],
    boolean
  >,
  /**
   * / Admin login using static credentials — returns session token on success
   */
  'adminLogin' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Check if user can proceed to payment (status must be priceSet)
   */
  'canUserPay' : ActorMethod<[string], boolean>,
  /**
   * / Confirm payment — admin only (moves from paymentPendingVerification to completed)
   */
  'confirmPayment' : ActorMethod<[string, string], boolean>,
  /**
   * / Get a single application by ID — accessible to users (own) or admins
   */
  'getApplication' : ActorMethod<[string], [] | [Application]>,
  /**
   * / Get applications filtered by status — admin only
   */
  'getApplicationsByStatus' : ActorMethod<
    [ApplicationStatus, string],
    Array<Application>
  >,
  /**
   * / User profile functions required by frontend
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get rejection message — open to anyone
   */
  'getRejectionMessage' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / "I Have Paid" — moves status to paymentPendingVerification
   */
  'markPaymentPendingVerification' : ActorMethod<[string], boolean>,
  /**
   * / Reject application and provide rejection message — admin only
   */
  'rejectApplication' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Set application fee (moves to priceSet) — admin only
   */
  'setApplicationFee' : ActorMethod<[string, bigint, string], boolean>,
  /**
   * / Update application status — admin only
   */
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];