/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'feeSet' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'paymentVerifying' : IDL.Null,
  'paymentPending' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'content' : ExternalBlob,
  'name' : IDL.Text,
});
export const RejectionInfo = IDL.Record({
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'status' : ApplicationStatus,
  'applicantName' : IDL.Text,
  'documents' : IDL.Vec(Document),
  'rejection' : IDL.Opt(RejectionInfo),
  'stage' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
  'transactionId' : IDL.Opt(IDL.Text),
});
export const ManagerNotification = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'serviceId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const ApplicationFormData = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'applicantName' : IDL.Text,
  'documents' : IDL.Vec(Document),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canUserPay' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'confirmPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getActivePaymentPrice' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getAllNotifications' : IDL.Func(
      [],
      [IDL.Vec(ManagerNotification)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
  'getApplicationFee' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getApplicationsByStatus' : IDL.Func(
      [ApplicationStatus, IDL.Text],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getManagerNotifications' : IDL.Func([], [IDL.Vec(ManagerNotification)], []),
  'getPaymentDetails' : IDL.Func(
      [],
      [
        IDL.Record({
          'qr' : IDL.Opt(ExternalBlob),
          'upiDetails' : IDL.Text,
          'amount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPaymentIntentURL' : IDL.Func([], [IDL.Text], ['query']),
  'getRejectionReason' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RejectionInfo)],
      ['query'],
    ),
  'getServicePrice' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserApplications' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPaymentActive' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setActivePrice' : IDL.Func([IDL.Nat], [], []),
  'setApplicationFee' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
  'setServicePrice' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'submitApplication' : IDL.Func([ApplicationFormData], [Application], []),
  'submitPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateApplicationStage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'feeSet' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'paymentVerifying' : IDL.Null,
    'paymentPending' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({ 'content' : ExternalBlob, 'name' : IDL.Text });
  const RejectionInfo = IDL.Record({
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'status' : ApplicationStatus,
    'applicantName' : IDL.Text,
    'documents' : IDL.Vec(Document),
    'rejection' : IDL.Opt(RejectionInfo),
    'stage' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const ManagerNotification = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'serviceId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const ApplicationFormData = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'applicantName' : IDL.Text,
    'documents' : IDL.Vec(Document),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canUserPay' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'clearNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'confirmPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getActivePaymentPrice' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getAllNotifications' : IDL.Func(
        [],
        [IDL.Vec(ManagerNotification)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
    'getApplicationFee' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getApplicationsByStatus' : IDL.Func(
        [ApplicationStatus, IDL.Text],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getManagerNotifications' : IDL.Func(
        [],
        [IDL.Vec(ManagerNotification)],
        [],
      ),
    'getPaymentDetails' : IDL.Func(
        [],
        [
          IDL.Record({
            'qr' : IDL.Opt(ExternalBlob),
            'upiDetails' : IDL.Text,
            'amount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPaymentIntentURL' : IDL.Func([], [IDL.Text], ['query']),
    'getRejectionReason' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RejectionInfo)],
        ['query'],
      ),
    'getServicePrice' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserApplications' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPaymentActive' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setActivePrice' : IDL.Func([IDL.Nat], [], []),
    'setApplicationFee' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
    'setServicePrice' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitApplication' : IDL.Func([ApplicationFormData], [Application], []),
    'submitPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateApplicationStage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };