/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'content' : ExternalBlob,
  'name' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'awaitingPrice' : IDL.Null,
  'completed' : IDL.Null,
  'paymentPendingVerification' : IDL.Null,
  'documentsUploaded' : IDL.Null,
  'priceSet' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'status' : ApplicationStatus,
  'documents' : IDL.Vec(Document),
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Document)],
      [IDL.Bool],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canUserPay' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'confirmPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
  'getApplicationsByStatus' : IDL.Func(
      [ApplicationStatus, IDL.Text],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRejectionMessage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPaymentPendingVerification' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApplicationFee' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Text, ApplicationStatus, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({ 'content' : ExternalBlob, 'name' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'awaitingPrice' : IDL.Null,
    'completed' : IDL.Null,
    'paymentPendingVerification' : IDL.Null,
    'documentsUploaded' : IDL.Null,
    'priceSet' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'status' : ApplicationStatus,
    'documents' : IDL.Vec(Document),
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Document)],
        [IDL.Bool],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canUserPay' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'confirmPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getApplication' : IDL.Func([IDL.Text], [IDL.Opt(Application)], ['query']),
    'getApplicationsByStatus' : IDL.Func(
        [ApplicationStatus, IDL.Text],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRejectionMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPaymentPendingVerification' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApplicationFee' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Text, ApplicationStatus, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };